### ISSUE TITLE
Not working on Centos/RHEL 7?

### ISSUE THREAD

**Issue by futureweb** [front/g-editor#8]
Hey there,
I tried to get g-editor working on one of our Centos 7 Hosts. But unfortunately it always fails ...
Maybe you got an idea what's wrong here?
thx, bye from Austria
Andreas

```
[root@localhost g-editor]# npm start          

> @frontkom/g-editor@1.3.0 start /daten/www/futureweb/g-editor
> node scripts/start.js

/daten/www/futureweb/g-editor/config/webpack.config.dev.js:344
      ...blockVars,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/daten/www/futureweb/g-editor/scripts/start.js:32:16)

npm ERR! Linux 3.10.0-957.10.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @frontkom/g-editor@1.3.0 start: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @frontkom/g-editor@1.3.0 start script 'node scripts/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @frontkom/g-editor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @frontkom/g-editor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @frontkom/g-editor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /daten/www/futureweb/g-editor/npm-debug.log




[root@localhost g-editor]# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.17.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @frontkom/g-editor@1.3.0~prestart: @frontkom/g-editor@1.3.0
6 silly lifecycle @frontkom/g-editor@1.3.0~prestart: no script for prestart, continuing
7 info lifecycle @frontkom/g-editor@1.3.0~start: @frontkom/g-editor@1.3.0
8 verbose lifecycle @frontkom/g-editor@1.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle @frontkom/g-editor@1.3.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/daten/www/futureweb/g-editor/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
10 verbose lifecycle @frontkom/g-editor@1.3.0~start: CWD: /daten/www/futureweb/g-editor
11 silly lifecycle @frontkom/g-editor@1.3.0~start: Args: [ '-c', 'node scripts/start.js' ]
12 silly lifecycle @frontkom/g-editor@1.3.0~start: Returned: code: 1  signal: null
13 info lifecycle @frontkom/g-editor@1.3.0~start: Failed to exec start script
14 verbose stack Error: @frontkom/g-editor@1.3.0 start: `node scripts/start.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid @frontkom/g-editor@1.3.0
16 verbose cwd /daten/www/futureweb/g-editor
17 error Linux 3.10.0-957.10.1.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.17.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error @frontkom/g-editor@1.3.0 start: `node scripts/start.js`
22 error Exit status 1
23 error Failed at the @frontkom/g-editor@1.3.0 start script 'node scripts/start.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the @frontkom/g-editor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node scripts/start.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs @frontkom/g-editor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls @frontkom/g-editor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by futureweb** [comment]
gicing up on this one ... guess need to wait a bit more until Gutenberg can really be used standalone ... :-/
